blueprint:
  name: Day Cycle Light Brightness
  description: Makes a light's brightness follow the day cycle
  domain: automation
  input:
    light_controller:
      name: Light
      description: This light's brightness will be synchronized with the day/night cycle.
      selector:
        target:
          entity:
            - domain: light
    base_value:
      name: Base brightness
      description: The brightness at sunrise and sunset.
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
    max_value:
      name: Maximum brightness
      description: Hard limit for the brightness.
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
    min_value:
      name: Minimum brightness
      description: Hard limit for the brightness.
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
    noon_value:
      name: Brightness at noon
      description: The brightness in the middle of the day. (May be higher/lower than the maximum/minimum brightness.)
      selector:
        number:
          min: -100
          max: 200
          step: 1
          unit_of_measurement: "%"
          mode: slider
    midnight_value:
      name: Brightness at midnight
      description: The brightness in the middle of the night. (May be higher/lower than the maximum/minimum brightness.)
      selector:
        number:
          min: -100
          max: 200
          step: 1
          unit_of_measurement: "%"
          mode: slider
    time_offset:
      name: Time offset
      description: Offset from the current time. Negative values will move the curve back, i.e. delay the brightness change. (May be unstable.)
      selector:
        number:
          min: -12
          max: 12
          step: 0.25
          unit_of_measurement: "h"
          mode: slider

trigger:
  - platform: time_pattern
    minutes: /1
condition: []

action:
  - variables:
      cc: !input light_controller
      dayt: !input noon_value
      nightt: !input midnight_value
      sett: !input base_value
      attday: "{{ dayt - sett }}"
      attnight: "{{ nightt - sett }}"
      maxt: !input max_value
      mint: !input min_value
      offset: !input time_offset
      se: >-
        {% set sr = state_attr('sun.sun','next_rising')|as_timestamp - today_at()|as_timestamp %}
        {% set sr = sr - [86400, 0][sr < 86400] %}
        {% set ss = state_attr('sun.sun','next_setting')|as_timestamp - today_at()|as_timestamp %}
        {% set ss = ss - [86400, 0][ss < 86400] %}
        {% set n = now()|as_timestamp + offset*60*60 - today_at()|as_timestamp %}
        {% set n = n + [0, 86400][n < sr] %}
        {% set dl = ss - sr if ss > sr else 86400 - (sr - ss) %}
        {{ ((-1, sin(pi * ((n - ss) / (dl - 86400), (n - sr) / dl)[ss > n > sr]), 1)|sort)[1] }}
      value: >-
        {{ ((mint, [sett - se * attnight, sett + se * attday][se > 0], maxt)|sort)[1] * 2.55 }}
  - if:
      - condition: template
        value_template: >-
          {{ (value - state_attr(cc.entity_id, 'brightness')|float)|abs > 1 }}
    then:
      - service: light.turn_on
        metadata: {}
        data:
          brightness: "{{value|int}}"
        target: !input light_controller
mode: single
